### ISSUE TITLE
Error on import with `0.2.0`

### ISSUE THREAD

**Issue by bjhardcastle** [AllenNeuralDynamics/wavpack-numcodecs#17]
`"libwavpack.so.1: cannot open shared object file: No such file or directory"`

- happens in `__init__.py` on import in a Code Ocean capsule running 3.9, `wavpack-numcodecs=0.2.0`

**Comment by alejoe91** [comment]
On it! For the time being, can you revert to 0.1.5?

**Comment by alejoe91** [comment]
@bjhardcastle now everything should work with version 0.2.1. Indeed there was a missing f-string in the runtime paths #18 

This opened up a bigger issue. The shipped wavpack library needs to be compatible with the system glibc library. To support multiple systems, I now made an [Action](https://github.com/AllenNeuralDynamics/wavpack-numcodecs/blob/main/.github/workflows/build-wavpack-binaries.yml) that builds wavpack against multiple ubuntu versions and automatically updates the binaries.
